import { useEffect, useState } from "react";
import { CheckCircle, Gift, XCircle } from "lucide-react";
import { getRewardClaims, REWARD_CLAIMS_UPDATED, reviewRewardClaim } from "../../utils/rewardClaims";

export default function RewardManagement() {
  const [claims, setClaims] = useState([]); const [notes, setNotes] = useState({});
  const load = () => setClaims(getRewardClaims());
  useEffect(() => { load(); window.addEventListener(REWARD_CLAIMS_UPDATED, load); window.addEventListener("storage", load); return () => { window.removeEventListener(REWARD_CLAIMS_UPDATED, load); window.removeEventListener("storage", load); }; }, []);
  const review = (id, status) => { reviewRewardClaim(id, status, notes[id] || ""); load(); };
  return <section className="mt-8 rounded-3xl border border-white/70 bg-white/80 p-6 shadow-lg"><div className="flex items-center gap-2"><Gift className="h-6 w-6 text-[#66785F]" /><div><h2 className="text-2xl font-bold text-[#2E332B]">Reward Management</h2><p className="text-sm text-gray-500">Review Hope Points reward claims and manually record fulfilment.</p></div></div>{claims.length ? <div className="mt-6 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#DCCFC0] text-xs uppercase text-gray-500"><tr><th className="p-3">User</th><th className="p-3">Hope Points</th><th className="p-3">Reward</th><th className="p-3">Request date</th><th className="p-3">Status</th><th className="p-3">Admin action</th></tr></thead><tbody>{claims.map((claim) => <tr key={claim.id} className="border-b border-[#F0E7DB]"><td className="p-3 font-semibold text-[#2E332B]">{claim.userName}</td><td className="p-3">{claim.hopePoints}</td><td className="p-3">₹{claim.rewardAmount}</td><td className="p-3">{new Date(claim.requestedAt).toLocaleDateString("en-IN")}</td><td className="p-3"><span className="rounded-full bg-[#F8F6F1] px-3 py-1 text-xs font-bold">{claim.status}</span></td><td className="p-3"><div className="flex min-w-[270px] flex-wrap gap-2"><input value={notes[claim.id] || ""} onChange={(e) => setNotes((old) => ({ ...old, [claim.id]: e.target.value }))} className="w-36 rounded-lg border border-[#DCCFC0] px-2 py-1 text-xs" placeholder="Internal note" />{claim.status === "Pending Approval" && <><button onClick={() => review(claim.id, "Approved")} className="rounded-lg bg-emerald-600 px-2 py-1 text-xs font-bold text-white"><CheckCircle className="mr-1 inline h-3.5 w-3.5" />Approve</button><button onClick={() => review(claim.id, "Rejected")} className="rounded-lg bg-red-600 px-2 py-1 text-xs font-bold text-white"><XCircle className="mr-1 inline h-3.5 w-3.5" />Reject</button></>}{claim.status === "Approved" && <button onClick={() => review(claim.id, "Reward Granted")} className="rounded-lg bg-[#66785F] px-2 py-1 text-xs font-bold text-white">Mark Granted</button>}</div></td></tr>)}</tbody></table></div> : <p className="mt-6 text-sm text-gray-500">No reward claims yet.</p>}</section>;
}
