import { Gift, Sparkles } from "lucide-react";
import toast from "react-hot-toast";
import { useEffect, useState } from "react";
import { getActiveRewardClaim, getUserRewardClaims, isRewardEligible, REWARD_AMOUNT, REWARD_CLAIMS_UPDATED, REWARD_THRESHOLD, submitRewardClaim } from "../utils/rewardClaims";

const formatDate = (date) => date ? new Date(date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—";

export default function RewardClaimPanel({ user, points }) {
  const [history, setHistory] = useState(() => getUserRewardClaims(user.id));
  const refresh = () => setHistory(getUserRewardClaims(user.id));
  useEffect(() => { window.addEventListener(REWARD_CLAIMS_UPDATED, refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener(REWARD_CLAIMS_UPDATED, refresh); window.removeEventListener("storage", refresh); }; }, [user.id]);
  const eligible = isRewardEligible(points);
  const activeClaim = getActiveRewardClaim(user.id);
  const claim = () => { const created = submitRewardClaim({ userId: user.id, userName: user.name, hopePoints: points }); if (!created) return toast.error(activeClaim ? "You already have an active reward claim." : `Reach ${REWARD_THRESHOLD} Hope Points to claim a reward.`); refresh(); toast.success("Reward claim submitted for admin approval."); };

  return <section className="overflow-hidden rounded-[1.75rem] border border-[#E5DBCE] bg-white shadow-[0_12px_32px_rgba(58,64,53,0.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_38px_rgba(58,64,53,0.13)]">
    <div className="border-b border-[#F0E7DB] bg-gradient-to-br from-[#F8F6F1] via-white to-[#F1F4EE] p-6 sm:p-7">
      <div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#66785F]"><Sparkles className="h-4 w-4" />Hope Points reward</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-[#2E332B]">Eligibility Status</h2><p className="mt-2 text-sm leading-6 text-gray-600">Your progress toward a ₹{REWARD_AMOUNT} community reward.</p></div><span className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold shadow-sm ${eligible ? "bg-emerald-100 text-emerald-800 ring-1 ring-emerald-200" : "bg-[#F0E7DB] text-[#2E332B]"}`}>{eligible ? "Eligible" : "Not eligible"}</span></div>
      <div className="mt-6 rounded-2xl border border-[#DCCFC0] bg-white p-5 shadow-sm"><div className="flex items-end justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-[.12em] text-gray-500">Current Hope Points</span><p className="mt-1 text-4xl font-bold tracking-tight text-[#2E332B]">{points}<span className="ml-1 text-base font-semibold text-gray-500">/ {REWARD_THRESHOLD}</span></p></div><Gift className="mb-1 h-6 w-6 text-[#66785F]" /></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-[#F0E7DB]"><div className="h-full rounded-full bg-[#66785F] transition-all" style={{ width: `${Math.min(100, (points / REWARD_THRESHOLD) * 100)}%` }} /></div></div>
      {eligible && !activeClaim && <button onClick={claim} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#66785F] px-5 py-3 text-sm font-bold text-white shadow-md transition duration-200 hover:-translate-y-0.5 hover:bg-[#2E332B] hover:shadow-lg"><Gift className="h-5 w-5" />Claim Reward (₹{REWARD_AMOUNT})</button>}
      {activeClaim && <p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">Reward claim status: {activeClaim.status}</p>}
    </div>
    <div className="p-6 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#66785F]">Your claims</p><h3 className="mt-1 text-lg font-bold text-[#2E332B]">Reward History</h3></div><Gift className="h-5 w-5 text-[#66785F]" /></div>{history.length ? <div className="mt-5 space-y-3">{history.map((item, index) => <article key={item.id} className="relative rounded-2xl border border-[#F0E7DB] bg-[#F8F6F1] p-4 transition hover:border-[#DCCFC0] hover:shadow-sm"><span className="absolute left-0 top-4 h-9 w-1 rounded-r-full bg-[#66785F]" /><div className="flex flex-col gap-3 pl-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-[#66785F]">Reward #{history.length - index}</p><p className="mt-1 text-lg font-bold text-[#2E332B]">₹{item.rewardAmount} Reward</p></div><span className="w-fit rounded-full bg-white px-3 py-1.5 text-xs font-bold text-[#66785F] shadow-sm">{item.status}</span></div><div className="mt-4 grid gap-3 border-t border-[#E9E0D5] pt-3 text-sm text-gray-600 sm:grid-cols-2"><p><span className="block text-[11px] font-bold uppercase tracking-wide text-gray-500">Requested</span>{formatDate(item.requestedAt)}</p><p><span className="block text-[11px] font-bold uppercase tracking-wide text-gray-500">Reviewed</span>{formatDate(item.reviewedAt)}</p></div>{item.adminNotes && <p className="mt-3 rounded-xl bg-white px-3 py-2.5 text-sm text-gray-700"><b className="text-[#2E332B]">Admin notes:</b> {item.adminNotes}</p>}</article>)}</div> : <p className="mt-5 rounded-2xl bg-[#F8F6F1] p-4 text-sm text-gray-500">Your reward claims will appear here.</p>}</div>
  </section>;
}
